<｜begin▁of▁sentence｜>You are an expert Python programmer.Your task is to write a Python function to solve a programming problem.

### Instruction:
Translate the following java code to python and enclose your solution inside ```python```:
```


import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class p02744 {

    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);
        int n = Integer.parseInt(scan.next());
        scan.close();

        List<String> list = func(n);

        for (String s : list) {
            System.out.println(s);
        }

    }

    private static List<String> func(int n) {
        List<String> list = new ArrayList<String>();
        if (n == 1) {
            list.add("a");
        } else {
            List<String> prevList = func(n - 1);
            for (String s : prevList) {
                // å«ã¾ãã¦ããæå¤§ã®æå­ãæ¢ç´¢
                char max = 'a';
                for (int i = 0; i < s.length(); i++) {
                    if (max < s.charAt(i)) {
                        max = s.charAt(i);
                    }
                }

                for (char c = 'a'; c <= max + 1; c++) {
                    String newString = s + c;
                    list.add(newString);
                }
            }
        }
        return list;
    }
}

```

### Response:
```python
def main():
    n = int(input())

    result = func(n)

    for s in result:
        print(s)

def func(n):
    result = []
    if n == 1:
        result.append("a")
    else:
        prev_result = func(n - 1)
        for s in prev_result:
            max_char = max(s)

            for c in range(ord(max_char)+1, ord('z')+2):
                new_string = s + chr(c)
                result.append(new_string)
    return result

if __name__ == "__main__":
    main()
```

This Python code does the same thing as the Java code. It reads an integer from the standard input, calls the `func` function with this integer as argument, and then prints the results. The `func` function generates all possible strings of length `n` by recursively appending characters to the strings generated by the `func` function for `n-1`. The `max` function is used to find the maximum character in the string, and the `chr` function is used to convert an ASCII value to a character. The `ord` function is used to convert a character to its ASCII value.
<|EOT|>
