Below is the equivalent Java code:

```java
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

public class Solution {
    private static final int MOD = 1_000_000_007;
    private static final Map<Long, Integer> cache = new HashMap<>();

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int L = scanner.nextInt();
        int R = scanner.nextInt();
        scanner.close();

        System.out.println(solve(L, R));
    }

    public static int solve(int L, int R) {
        long key = (((long) L) << 32) | R; // Combine L and R into a single key
        if (cache.containsKey(key)) {
            return cache.get(key);
        }

        if (L > R) return 0;
        if (L == 1) {
            int result = (1 + solve(2, R)) % MOD;
            cache.put(key, result);
            return result;
        }

        int result = (solve(L / 2, (R - 1) / 2) +
                      solve((L + 1) / 2, R / 2) +
                      solve((L + 1) / 2, (R - 1) / 2)) % MOD;

        cache.put(key, result);
        return result;
    }
}

```

Please note that, unlike Python's built-in `@lru_cache`, there is no direct built-in caching mechanism in Java. Instead, a `HashMap` is used to simulate memoization. Additionally, it's important to create a unique map key for each set of `L` and `R` values, which is why the `key` is generated by shifting `L` to the upper 32-bits and keeping `R` in the lower 32-bits of a 64-bit `long`. This is an effective technique provided that both `L` and `R` will always be non-negative and fit within a 32-bit signed integer range.

Here's an example test for this Java code:

Test input:
2 3

Expected output:
4
