python /home/changshu/CodeMind/DER/Translation/translate.py --model granite --dataset codenet --source_lang java --target_lang python --gpu_id 0 --cache_dir /home/shared/huggingface
python /home/changshu/CodeMind/DER/Translation/translate.py --model granite --dataset codenet --source_lang python --target_lang java --gpu_id 0 --cache_dir /home/shared/huggingface
python /home/changshu/CodeMind/DER/Translation/translate.py --model granite --dataset avatar --source_lang java --target_lang python --gpu_id 0 --cache_dir /home/shared/huggingface
python /home/changshu/CodeMind/DER/Translation/translate.py --model granite --dataset avatar --source_lang python --target_lang java --gpu_id 0 --cache_dir /home/shared/huggingface
python /home/changshu/CodeMind/DER/Translation/translate.py --model granite --dataset codenet --source_lang java --target_lang python --gpu_id 0 --cache_dir /home/shared/huggingface --use_misleading_test
python /home/changshu/CodeMind/DER/Translation/translate.py --model granite --dataset codenet --source_lang python --target_lang java --gpu_id 0 --cache_dir /home/shared/huggingface --use_misleading_test
python /home/changshu/CodeMind/DER/Translation/translate.py --model granite --dataset avatar --source_lang java --target_lang python --gpu_id 0 --cache_dir /home/shared/huggingface --use_misleading_test
python /home/changshu/CodeMind/DER/Translation/translate.py --model granite --dataset avatar --source_lang python --target_lang java --gpu_id 0 --cache_dir /home/shared/huggingface --use_misleading_test
python /home/changshu/CodeMind/DER/Translation/translate.py --model granite --dataset codenet --source_lang java --target_lang python --gpu_id 0 --cache_dir /home/shared/huggingface --use_test
python /home/changshu/CodeMind/DER/Translation/translate.py --model granite --dataset codenet --source_lang python --target_lang java --gpu_id 0 --cache_dir /home/shared/huggingface --use_test
python /home/changshu/CodeMind/DER/Translation/translate.py --model granite --dataset avatar --source_lang java --target_lang python --gpu_id 0 --cache_dir /home/shared/huggingface --use_test
python /home/changshu/CodeMind/DER/Translation/translate.py --model granite --dataset avatar --source_lang python --target_lang java --gpu_id 0 --cache_dir /home/shared/huggingface --use_test